"""Ajout de HeartRateSample

Revision ID: 0f4252dc23ef
Revises: fa6ac29ef0b8
Create Date: 2025-05-10 11:35:04.556283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4252dc23ef'
down_revision = 'fa6ac29ef0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heart_rate_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['strava_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strava_activity', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('hr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strava_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hr', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('heart_rate_sample')
    # ### end Alembic commands ###
