"""Ajout de pr

Revision ID: 52a4801e0dab
Revises: 89b424f5b523
Create Date: 2025-05-08 18:52:13.677045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a4801e0dab'
down_revision = '89b424f5b523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pr', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.drop_column('pr')

    # ### end Alembic commands ###
