"""Changement du type de weight de Float à Integer

Revision ID: 89b424f5b523
Revises: 5f0a2de172bc
Create Date: 2025-05-07 11:17:47.603877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b424f5b523'
down_revision = '5f0a2de172bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.alter_column('added_weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.alter_column('added_weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
