"""Suppression weight

Revision ID: b40a3b367892
Revises: e0cac53668a2
Create Date: 2025-05-07 10:59:45.298613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40a3b367892'
down_revision = 'e0cac53668a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
