"""Ajout weight

Revision ID: e0cac53668a2
Revises: fe5fa6a9b518
Create Date: 2025-05-07 10:23:40.624417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cac53668a2'
down_revision = 'fe5fa6a9b518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_weight', sa.Integer(), nullable=True))
        batch_op.drop_column('weight')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weight')

    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.INTEGER(), nullable=True))
        batch_op.drop_column('added_weight')

    # ### end Alembic commands ###
