"""Ajout bodyweight

Revision ID: fe5fa6a9b518
Revises: 
Create Date: 2025-05-07 10:20:50.117452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5fa6a9b518'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bodyweight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.drop_column('bodyweight')

    # ### end Alembic commands ###
